### ISSUE TITLE
Any object user / game / service / team must have unique uuid field

### ISSUE THREAD

**Issue by sea-kg** [sea-kg/ctf01d-training-platform#14]
It's need for export/import objects from to simular systems

**Comment by IgorPolyakov** [comment]
@sea-kg Do you suggest changing the `id` to a `uuid`?

if yes, then no problem)

**Comment by sea-kg** [comment]
@IgorPolyakov 
Anyway need uuid - will be changed id to uuid field or added just a new field - don't matter. How are will be right?

**Comment by IgorPolyakov** [comment]
I would change the number ID to uuid. At least so as not to duplicate the keys

It's safer that way. In addition, postgres normally works with uuid as the primary key

**Comment by sea-kg** [comment]
Okay

**Comment by IgorPolyakov** [comment]
done in #18
