### ISSUE TITLE
Wanna new server api handler `/api/v1/auth/session`

### ISSUE THREAD

**Issue by sea-kg** [sea-kg/ctf01d-training-platform#16]
Wanna new handler `/api/auth/session` - validation current session.

1. Valid or not current session
2. Return current role of user.

It need for a UI - show/hide signin button ant another functions

**Comment by IgorPolyakov** [comment]
Ok?

**Comment by sea-kg** [comment]
> Ok?
Yes) tnx!

**Comment by IgorPolyakov** [comment]
done in #25
